from __future__ import annotations

"""Runtime helpers for applying measured Triton kernel selector artifacts."""

import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class TritonKernelConfig:
    rows: int
    cols: int
    batch: int
    high_every: int | None
    block_m: int
    block_n: int
    block_k: int
    status: str
    speedup_vs_fp16: float | None
    speedup_vs_rowwise: float | None
    rel_l2: float | None
    source: str

    def as_runtime_dict(self) -> dict[str, Any]:
        return {
            "rows": self.rows,
            "cols": self.cols,
            "batch": self.batch,
            "high_every": self.high_every,
            "block_m": self.block_m,
            "block_n": self.block_n,
            "block_k": self.block_k,
            "status": self.status,
            "speedup_vs_fp16": self.speedup_vs_fp16,
            "speedup_vs_rowwise": self.speedup_vs_rowwise,
            "rel_l2": self.rel_l2,
            "source": self.source,
        }


def _finite_float(value: Any) -> float | None:
    if value is None:
        return None
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    if not math.isfinite(number):
        return None
    return number


def _int_or_none(value: Any) -> int | None:
    if value is None:
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def load_kernel_configs(path: Path) -> list[TritonKernelConfig]:
    """Load selector output generated by select_triton_kernel_configs.py."""

    data = json.loads(path.read_text(encoding="utf-8"))
    configs: list[TritonKernelConfig] = []
    for item in data.get("selected_configs", []):
        selected = item.get("selected")
        if not selected:
            continue
        rows = _int_or_none(selected.get("rows", item.get("rows")))
        cols = _int_or_none(selected.get("cols", item.get("cols")))
        batch = _int_or_none(selected.get("batch", item.get("batch")))
        block_m = _int_or_none(selected.get("block_m"))
        block_n = _int_or_none(selected.get("block_n"))
        block_k = _int_or_none(selected.get("block_k"))
        if None in (rows, cols, batch, block_m, block_n, block_k):
            continue
        configs.append(
            TritonKernelConfig(
                rows=int(rows),
                cols=int(cols),
                batch=int(batch),
                high_every=_int_or_none(selected.get("high_every", item.get("high_every"))),
                block_m=int(block_m),
                block_n=int(block_n),
                block_k=int(block_k),
                status=str(item.get("status", "unknown")),
                speedup_vs_fp16=_finite_float(selected.get("grouped_speedup_vs_torch_fp16")),
                speedup_vs_rowwise=_finite_float(selected.get("grouped_speedup_vs_rowwise")),
                rel_l2=_finite_float(selected.get("grouped_rel_l2")),
                source=str(path),
            )
        )
    return configs


def estimate_periodic_high_every(row_bits: Any) -> int | None:
    """Infer a simple every-N high-precision row pattern when present."""

    try:
        values = [int(value) for value in row_bits]
    except TypeError:
        return None
    high = [idx for idx, value in enumerate(values) if value == 8]
    if len(high) < 2:
        return None
    diffs = [right - left for left, right in zip(high, high[1:])]
    if not diffs or any(diff <= 0 for diff in diffs):
        return None
    first = diffs[0]
    if all(diff == first for diff in diffs):
        return first
    return None


def _batch_distance(candidate: int, batch: int) -> tuple[float, int]:
    if candidate <= 0 or batch <= 0:
        return (float("inf"), abs(candidate - batch))
    return (abs(math.log2(candidate / batch)), abs(candidate - batch))


def choose_kernel_config(
    configs: list[TritonKernelConfig],
    *,
    rows: int,
    cols: int,
    batch: int,
    high_every: int | None = None,
    prefer_fp16_win: bool = False,
) -> TritonKernelConfig | None:
    """Choose the nearest measured config for a runtime module invocation."""

    candidates = [cfg for cfg in configs if cfg.rows == rows and cfg.cols == cols]
    if high_every is not None:
        exact = [cfg for cfg in candidates if cfg.high_every == high_every]
        if exact:
            candidates = exact
    if not candidates:
        return None

    def key(cfg: TritonKernelConfig) -> tuple[float, int, int, float, float]:
        batch_dist, batch_abs = _batch_distance(cfg.batch, batch)
        fp16_rank = 0 if (prefer_fp16_win and cfg.status == "fp16_win") else 1
        speedup = cfg.speedup_vs_fp16 if cfg.speedup_vs_fp16 is not None else -1.0
        rowwise = cfg.speedup_vs_rowwise if cfg.speedup_vs_rowwise is not None else -1.0
        return (batch_dist, batch_abs, fp16_rank, -speedup, -rowwise)

    return min(candidates, key=key)
